// === マクロ内容 ===================================================
// 選択範囲をjavascriptとして実行する。
// 実行時のファイル最下部に出力結果を出力する。
// 出力には、echo(text)を利用できる。
// 
// 
// ■サンプル
// for (var i = 0; i <= 10; i++) {
// 	echo(i + ", ");
// }
// 
// ===============================================================

(function() {
	// サクラエディタマクロ中で利用する用の変数・関数群。
	var macro = {
		selectedString : Editor.GetSelectedString(0),
		lineSeparator : "\r\n"
	};

	Editor.GoFileEnd();
	Editor.InsText(macro.lineSeparator);
	Editor.InsText(macro.lineSeparator);
	Editor.InsText("// === javascript実行結果 ========================="
			+ macro.lineSeparator);
	eval(macro.selectedString);

	// 出力関数のエイリアス
	function echo(text) {
		Editor.InsText(text);
	}
})();

// === 予測変換用の関数定義領域 ========================
// Editor
// ファイル操作
// FileNew
// FileOpen
// FileSave
// FileSaveAll
// FileSaveAs
// FileClose
// FileCloseOpen
// FileReopen
// FileReopenSJIS
// FileReopenJIS
// FileReopenEUC
// FileReopenUNICODE
// FileReopenUNICODEBE
// FileReopenUTF8
// FileReopenUTF7
// Print
// PrintPreview
// PrintPageSetup
// OpenHfromtoC
// OpenHHpp
// OpenCCpp
// ActivateSQLPLUS
// ExecSQLPLUS
// Browse
// ReadOnly
// PropertyFile
// ExitAll
// 編集
// Char
// CharIme
// Undo
// Redo
// Delete
// DeleteBack
// WordDeleteToStart
// WordDeleteToEnd
// WordCut
// WordDelete
// LineCutToStart
// LineCutToEnd
// LineDeleteToStart
// LineDeleteToEnd
// CutLine
// DeleteLine
// DuplicateLine
// IndentTab
// UnindentTab
// IndentSpace
// UnindentSpace
// LTrim
// RTrim
// SortAsc
// SortDesc
// Merge
// カーソル移動
// Up
// Down
// Left
// Right
// Up2
// Down2
// WordLeft
// WordRight
// GoLineTop
// GoLineEnd
// HalfPageUp
// HalfPageDown
// 1PageUp
// 1PageDown
// GoFileTop
// GoFileEnd
// CurLineCenter
// MoveHistPrev
// MoveHistNext
// MoveHistSet
// F_WndScrollDown
// F_WndScrollUp
// GoNextParagraph
// GoPrevParagraph
// 選択
// SelectWord
// SelectAll
// BeginSelect
// Up_Sel
// Down_Sel
// Left_Sel
// Right_Sel
// Up2_Sel
// Down2_Sel
// WordLeft_Sel
// WordRight_Sel
// GoLineTop_Sel
// GoLineEnd_Sel
// HalfPageUp_Sel
// HalfPageDown_Sel
// 1PageUp_Sel
// 1PageDown_Sel
// GoFileTop_Sel
// GoFileEnd_Sel
// GoNextParagraph_Sel
// GoPrevParagraph_Sel
// 矩形選択
// BeginBoxSelect
// クリップボード
// Cut
// Copy
// Paste
// CopyAddCRLF
// CopyCRLF
// PasteBox
// InsText
// AddTail
// CopyLines
// CopyLinesAsPassage
// CopyLinesWithLineNumber
// CopyPath
// CopyFilename
// CopyTag
// CopyKeyBindList
// 挿入
// InsertDate
// InsertTime
// CtrlCodeDialog
// 変換
// ToLower
// ToUpper
// ToHankaku
// ToHankata
// ToZenEi
// ToHanEi
// ToZenKata
// ToZenHira
// HanKataToZenKata
// HanKataToZenHira
// TABToSPACE
// SPACEToTAB
// AutoToSJIS
// JIStoSJIS
// EUCtoSJIS
// CodeCnvUNICODEtoSJIS
// CodeCnvUNICODEBEtoSJIS
// UTF8toSJIS
// UTF7toSJIS
// SJIStoJIS
// SJIStoEUC
// SJIStoUTF8
// SJIStoUTF7
// Base64Decode
// Uudecode
// 検索
// SearchDialog
// SearchNext
// SearchPrev
// ReplaceDialog
// Replace
// ReplaceAll
// ReplaceAllLine
// SearchClearMark
// SearchStartPos
// Grep
// Jump
// Outline
// TagJump
// TagJumpBack
// TagMake
// DirectTagJump
// Compare
// DiffDialog
// Diff
// DiffNext
// DiffPrev
// DiffReset
// BracketPair
// BookmarkSet
// BookmarkNext
// BookmarkPrev
// BookmarkReset
// BookmarkView
// BookmarkPattern
// モード切替
// ChgmodINS
// ChgmodEOL
// CancelMode
// 設定
// ShowToolbar
// ShowFunckey
// ShowTab
// ShowStatusbar
// TypeList
// OptionType
// OptionCommon
// SelectFont
// WrapWindowWidth
// OptionFavorite
// SetMsgQuoteStr
// ExecCommand
// カスタムメニュー
// RMenu
// CustMenu1
// CustMenu2
// CustMenu3
// CustMenu4
// CustMenu5
// CustMenu6
// CustMenu7
// CustMenu8
// CustMenu9
// CustMenu10
// CustMenu11
// CustMenu12
// CustMenu13
// CustMenu14
// CustMenu15
// CustMenu16
// CustMenu17
// CustMenu18
// CustMenu19
// CustMenu20
// CustMenu21
// CustMenu22
// CustMenu23
// CustMenu24
// ウインドウ
// SplitWinV
// SplitWinH
// SplitWinVH
// WinClose
// WinCloseAll
// CascadeWin
// TileWinV
// TileWinH
// NextWindow
// PrevWindow
// MaximizeV
// MaximizeH
// MinimizeAll
// ReDraw
// ActivateWinOutput
// WindowTopMost
// 支援
// Complete
// HelpContents
// HelpSearch
// CommandList
// ExtHelp1
// ExtHtmlHelp
// About
// その他
// GetFilename
// GetSelectedString
// ExpandParameter
// GetLineStr
// GetLineCount
// ChangeTabWidth
// IsTextSelected
// GetSelectLineFrom
// GetSelectColmFrom
// GetSelectLineTo
// GetSelectColmTo
// IsInsMode
// GetCharCode
// GetLineCode
// IsPossibleUndo
// IsPossibleRedo
// TraceOut
